[package]
name = "sophi"
version = "0.1.0"
edition = "2024"
authors = ["ReinanBr"]
description = "Math Physics library in rust"
license = "MIT or BSD-0-Clause"
homepage = "https://github.com/reinanbr/sophi"
repository = "https://github.com/reinanbr/sophi"
readme = "README.md"
keywords = ["math", "physics", "rust"]
categories = ["math", "physics"]

[dependencies]
