[package]
name = "sophi"
version = "0.1.3"
edition = "2024"
authors = ["ReinanBr"]
description = "Math Physics library in rust"
license = "MIT"
homepage = "https://github.com/reinanbr/sophi"
repository = "https://github.com/reinanbr/sophi"
readme = "README.md"
keywords = ["math", "physics", "rust"]


[dependencies]
